site:
  title: Integration test
  start_page: antora-tools-graphql::index.adoc
antora:
  extensions:
    - require: '@antora-tools/graphql'
      strategy: BIER #FILE
      location: '../../test/schemas/*.graphql'
      meta_file: './metadata.json'
      intro: |
        Welcome to the **GraphQL Demo** pages.
content:
  sources:
    - url: ../../../..
      start_path: packages/graphql/docs
ui:
  bundle:
    url: ./ui-bundle.zip
