name: '@antora-tools/graphql (e2e)'
on:
  push:
    paths:
      - 'packages/graphql/**'
      - '.github/workflows/graphql-e2e.yml'
    branches: [main]
  pull_request:
    paths:
      - 'packages/graphql/**'
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        working-directory: ./packages/graphql
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
        working-directory: ./packages/graphql
      - name: Run E2E tests
        run: npm run test:e2e
        working-directory: ./packages/graphql
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
